exports.queryList = {

    getStoreListQuery : `SELECT STORE_ID, STORE_NAME, DESCRIPTION, STORE_CODE, CREATED_ON, CREATED_BY, ACTIVE
    FROM BMS.STORE;`,

    saveStoreQuery : `INSERT INTO BMS.STORE
    ( STORE_NAME, DESCRIPTION, STORE_CODE, ADDRESS, CREATED_ON, CREATED_BY )
    VALUES($1,$2 ,$3 ,$4 ,$5 ,$6); `

};

